modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Nightware"
description='''
Play custom MP3 files in-game via server commands. Supports looping, seeking and finite playback durations.
'''

[[dependencies.${mod_id}]]
    modId="kubejs"
    type="optional"
    versionRange="[2101,)"
    ordering="NONE"
    side="CLIENT"
